apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ${CLUSTER_NAME}-data-services
  namespace: ${CLUSTER_NAMESPACE}
spec:
  dependsOn:
    - name: ${CLUSTER_NAME}-workload
  interval: 10m
  retryInterval: 1m
  timeout: 30m
  path: ./apps/data-services
  prune: false
  wait: true
  sourceRef:
    kind: GitRepository
    name: layersentry-e1-catalog
    namespace: flux-system
  kubeConfig:
    secretRef:
      name: ${CLUSTER_NAME}-kubeconfig
      key: value
  postBuild:
    substitute:
      LAYERSENTRY_OPENEVEREST_HELM_GIT_URL: https://github.com/openeverest/helm-charts.git
    substituteFrom:
      - kind: ConfigMap
        name: ${CLUSTER_NAME}-site-config
        optional: true
