apiVersion: v1
kind: Namespace
metadata:
  name: everest-system
  labels:
    app.kubernetes.io/part-of: layersentry-dbaas
---
apiVersion: v1
kind: Namespace
metadata:
  name: layersentry-dbaas
  labels:
    app.kubernetes.io/part-of: layersentry-dbaas
