telemetry: false

server:
  service:
    type: ClusterIP
  rbac:
    enabled: true
    policy: |
      g, admin, role:admin
  tls:
    enabled: true
    certificate:
      create: true
      domain: everest.everest-system.svc
      additionalHosts:
        - everest.everest-system.svc.cluster.local
      issuer:
        group: ${LAYERSENTRY_DBAAS_CERT_ISSUER_GROUP:=cert-manager.io}
        kind: ${LAYERSENTRY_DBAAS_CERT_ISSUER_KIND:=ClusterIssuer}
        name: ${LAYERSENTRY_DBAAS_CERT_ISSUER_NAME}
    secret:
      name: everest-server-tls
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

operator:
  enableLeaderElection: true
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi

dbNamespace:
  enabled: true
  namespaceOverride: layersentry-dbaas

olm:
  install: true

monitoring:
  enabled: true

kube-state-metrics:
  enabled: true

pmm:
  enabled: false
pmm3:
  enabled: false

ingress:
  enabled: false
gatewayAPI:
  enabled: false
