apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ccm.yaml
- csi-rbac.yaml
- csi-csidriver.yaml
- csi-controller-deployment.yaml
- csi-node-daemonset.yaml
- csi-00-snapshot-crds.yaml
